eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka #多实例高可用
    register-with-eureka: false #不注册到server
    fetch-registry: false #不从server获取信息
  server:
    enable-self-preservation: false #自我保护模式 短时间内client掉线，不删除实例

spring:
  application:
    name: eureka

server:
  port: 8761