spring:
  datasource:
    url: jdbc:mysql://10.2.27.112/sell?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: mysqluser
    password: MySQL_user123

  jpa:
    show-sql: true

  jackson:
    default-property-inclusion: non_null #含null的对象json不序列化,先依赖gson

  redis:
    host: 10.2.26.223
    port: 6379
#    password:

server:
  servlet:
    context-path: /sell


projecturl:
  sell: http://127.0.0.1:8080